version: 2.1
jobs:
  discovery-service:
    docker:
      - image: spuyo/discovery-service
    steps:
      - checkout
      - run:
          name: Hello
          command: echo "Hello spuyo - I am running the discovery-service" && ls
workflows:
  spuyo:
    jobs:
      - discovery-service